package mpm.ig.mission.model;

// Generated 25 août 2016 12:36:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name = "document", catalog = "siig")
public class Document implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idDoc;
	private Soustypedoc soustypedoc;
	private String titre;
	private Date dateAjout;
	private String description;
	private byte[] doc;
	
	private Set<Missionpj> missionpjs = new HashSet<Missionpj>(0);
	private Set<Consultation> consultations = new HashSet<Consultation>(0);

	public Document() {
	}

	public Document(Soustypedoc soustypedoc) {
		this.soustypedoc = soustypedoc;
	}

	public Document(Soustypedoc soustypedoc, String titre, Date dateAjout,
			String description, byte[] doc, Set<Missionpj> missionpjs,
			Set<Consultation> consultations) {
		this.soustypedoc = soustypedoc;
		this.titre = titre;
		this.dateAjout = dateAjout;
		this.description = description;
		this.doc = doc;
		this.missionpjs = missionpjs;
		this.consultations = consultations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idDoc", unique = true, nullable = false)
	public Integer getIdDoc() {
		return this.idDoc;
	}

	public void setIdDoc(Integer idDoc) {
		this.idDoc = idDoc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSousType", nullable = false)
	public Soustypedoc getSoustypedoc() {
		return this.soustypedoc;
	}

	public void setSoustypedoc(Soustypedoc soustypedoc) {
		this.soustypedoc = soustypedoc;
	}

	@Column(name = "titre", length = 254)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateAjout", length = 10)
	public Date getDateAjout() {
		return this.dateAjout;
	}

	public void setDateAjout(Date dateAjout) {
		this.dateAjout = dateAjout;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "doc")
	public byte[] getDoc() {
		return this.doc;
	}

	public void setDoc(byte[] doc) {
		this.doc = doc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "document")
	public Set<Missionpj> getMissionpjs() {
		return this.missionpjs;
	}

	public void setMissionpjs(Set<Missionpj> missionpjs) {
		this.missionpjs = missionpjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "document")
	public Set<Consultation> getConsultations() {
		return this.consultations;
	}

	public void setConsultations(Set<Consultation> consultations) {
		this.consultations = consultations;
	}

}
