package mpm.ig.mission.model;

// Generated 25 août 2016 12:36:11 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entite generated by hbm2java
 */
@Entity
@Table(name = "entite", catalog = "siig")
public class Entite implements java.io.Serializable {

	private Integer idEntite;
	private Ville ville;
	private String intitule;
	private Set<Destination> destinations = new HashSet<Destination>(0);

	public Entite() {
	}
	
	public Entite(int idEntite)
	{
		this.idEntite = idEntite;
	}
	
	public Entite(Ville ville, String intitule, Set<Destination> destinations) {
		this.ville = ville;
		this.intitule = intitule;
		this.destinations = destinations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEntite", unique = true, nullable = false)
	public Integer getIdEntite() {
		return this.idEntite;
	}

	public void setIdEntite(Integer idEntite) {
		this.idEntite = idEntite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idVille")
	public Ville getVille() {
		return this.ville;
	}

	public void setVille(Ville ville) {
		this.ville = ville;
	}

	@Column(name = "intitule", length = 254)
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "entite")
	public Set<Destination> getDestinations() {
		return this.destinations;
	}

	public void setDestinations(Set<Destination> destinations) {
		this.destinations = destinations;
	}

}
