package mpm.ig.mission.model;

// Generated 25 août 2016 12:36:11 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Membreequipe generated by hbm2java
 */
@Entity
@Table(name = "membreequipe", catalog = "siig")
public class Membreequipe implements java.io.Serializable {

	private Integer idMe;
	private User user;
	private Mission mission;
	private String fonction;

	public Membreequipe() {
	}

	public Membreequipe(User user, Mission mission) {
		this.user = user;
		this.mission = mission;
	}

	public Membreequipe(User user, Mission mission, String fonction) {
		this.user = user;
		this.mission = mission;
		this.fonction = fonction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMe", unique = true, nullable = false)
	public Integer getIdMe() {
		return this.idMe;
	}

	public void setIdMe(Integer idMe) {
		this.idMe = idMe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMission", nullable = false)
	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	@Column(name = "fonction", length = 254)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

}
