package mpm.ig.mission.model;

// Generated 25 août 2016 12:36:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Missionpj generated by hbm2java
 */
@Entity
@Table(name = "missionpj", catalog = "siig")
public class Missionpj implements java.io.Serializable {

	private Integer idPj;
	private Mission mission;
	private Typepj typepj;
	private Document document;
	private String titre;
	private Date dateAjout;
	private String description;

	public Missionpj() {
	}

	public Missionpj(Mission mission, Typepj typepj, Document document) {
		this.mission = mission;
		this.typepj = typepj;
		this.document = document;
	}

	public Missionpj(Mission mission, Typepj typepj, Document document,
			String titre, Date dateAjout, String description) {
		this.mission = mission;
		this.typepj = typepj;
		this.document = document;
		this.titre = titre;
		this.dateAjout = dateAjout;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPj", unique = true, nullable = false)
	public Integer getIdPj() {
		return this.idPj;
	}

	public void setIdPj(Integer idPj) {
		this.idPj = idPj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMission", nullable = false)
	public Mission getMission() {
		return this.mission;
	}

	public void setMission(Mission mission) {
		this.mission = mission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idType", nullable = false)
	public Typepj getTypepj() {
		return this.typepj;
	}

	public void setTypepj(Typepj typepj) {
		this.typepj = typepj;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDoc", nullable = false)
	public Document getDocument() {
		return this.document;
	}

	public void setDocument(Document document) {
		this.document = document;
	}

	@Column(name = "titre", length = 254)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dateAjout", length = 10)
	public Date getDateAjout() {
		return this.dateAjout;
	}

	public void setDateAjout(Date dateAjout) {
		this.dateAjout = dateAjout;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
