package mpm.ig.mission.model;

// Generated 25 août 2016 12:36:11 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mission generated by hbm2java
 */
@Entity
@Table(name = "mission", catalog = "siig")
public class Mission implements java.io.Serializable {

	private Integer idMission;
	private Typemission typemission;
	private String titre;
	private Date debut;
	private Date fin;
	private String objet;
	private String detail;
	private String etat;
	private Set<Membreequipe> membreequipes = new HashSet<Membreequipe>(0);
	private Set<Missionpj> missionpjs = new HashSet<Missionpj>(0);
	private Set<Destination> destinations = new HashSet<Destination>(0);

	public Mission() {
	}

	public Mission(Typemission typemission, String titre, Date debut, Date fin,
			String objet, String detail, String etat,
			Set<Membreequipe> membreequipes, Set<Missionpj> missionpjs,
			Set<Destination> destinations) {
		this.typemission = typemission;
		this.titre = titre;
		this.debut = debut;
		this.fin = fin;
		this.objet = objet;
		this.detail = detail;
		this.etat = etat;
		this.membreequipes = membreequipes;
		this.missionpjs = missionpjs;
		this.destinations = destinations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMission", unique = true, nullable = false)
	public Integer getIdMission() {
		return this.idMission;
	}

	public void setIdMission(Integer idMission) {
		this.idMission = idMission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idType")
	public Typemission getTypemission() {
		return this.typemission;
	}

	public void setTypemission(Typemission typemission) {
		this.typemission = typemission;
	}

	@Column(name = "titre", length = 254)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "debut", length = 10)
	public Date getDebut() {
		return this.debut;
	}

	public void setDebut(Date debut) {
		this.debut = debut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fin", length = 10)
	public Date getFin() {
		return this.fin;
	}

	public void setFin(Date fin) {
		this.fin = fin;
	}

	@Column(name = "objet", length = 254)
	public String getObjet() {
		return this.objet;
	}

	public void setObjet(String objet) {
		this.objet = objet;
	}

	@Column(name = "detail", length = 254)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mission")
	public Set<Membreequipe> getMembreequipes() {
		return this.membreequipes;
	}

	public void setMembreequipes(Set<Membreequipe> membreequipes) {
		this.membreequipes = membreequipes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mission")
	public Set<Missionpj> getMissionpjs() {
		return this.missionpjs;
	}

	public void setMissionpjs(Set<Missionpj> missionpjs) {
		this.missionpjs = missionpjs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mission")
	public Set<Destination> getDestinations() {
		return this.destinations;
	}

	public void setDestinations(Set<Destination> destinations) {
		this.destinations = destinations;
	}

}
