package mpm.ig.mission.model;

// Generated 25 août 2016 12:36:11 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "profil", catalog = "siig")
public class Profil implements java.io.Serializable {

	private Integer idP;
	private String code;
	private String libelle;
	private Set<Account> accounts = new HashSet<Account>(0);

	public Profil() {
	}

	public Profil(String code, String libelle, Set<Account> accounts) {
		this.code = code;
		this.libelle = libelle;
		this.accounts = accounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idP", unique = true, nullable = false)
	public Integer getIdP() {
		return this.idP;
	}

	public void setIdP(Integer idP) {
		this.idP = idP;
	}

	@Column(name = "code", length = 254)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "libelle", length = 254)
	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profil")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
