package mpm.ig.mission.model;

// Generated 25 août 2016 12:36:11 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "siig")
public class User implements java.io.Serializable {

	private Integer idUser;
	private Integer ppr;
	private String cin;
	private String nom;
	private String prenom;
	private Set<Consultation> consultations = new HashSet<Consultation>(0);
	private Set<Membreequipe> membreequipes = new HashSet<Membreequipe>(0);
	private Set<Account> accounts = new HashSet<Account>(0);

	public User() {
	}
	
	public User(int idUser)
	{
		this.idUser = idUser;
	}
	
	public User(Integer ppr, String cin, String nom, String prenom,
			Set<Consultation> consultations, Set<Membreequipe> membreequipes,
			Set<Account> accounts) {
		this.ppr = ppr;
		this.cin = cin;
		this.nom = nom;
		this.prenom = prenom;
		this.consultations = consultations;
		this.membreequipes = membreequipes;
		this.accounts = accounts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUser", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "ppr", precision = 8, scale = 0)
	public Integer getPpr() {
		return this.ppr;
	}

	public void setPpr(Integer ppr) {
		this.ppr = ppr;
	}

	@Column(name = "cin", length = 254)
	public String getCin() {
		return this.cin;
	}

	public void setCin(String cin) {
		this.cin = cin;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Consultation> getConsultations() {
		return this.consultations;
	}

	public void setConsultations(Set<Consultation> consultations) {
		this.consultations = consultations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Membreequipe> getMembreequipes() {
		return this.membreequipes;
	}

	public void setMembreequipes(Set<Membreequipe> membreequipes) {
		this.membreequipes = membreequipes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
