package mpm.ig.mission.model;

// Generated 25 août 2016 12:36:11 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ville generated by hbm2java
 */
@Entity
@Table(name = "ville", catalog = "siig")
public class Ville implements java.io.Serializable {

	private Integer idVille;
	private String intitule;
	private Set<Destination> destinations = new HashSet<Destination>(0);
	private Set<Entite> entites = new HashSet<Entite>(0);

	public Ville() {
	}
	
	public Ville(int idVille)
	{
		this.idVille = idVille;
	}
	
	public Ville(String intitule, Set<Destination> destinations,
			Set<Entite> entites) {
		this.intitule = intitule;
		this.destinations = destinations;
		this.entites = entites;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVille", unique = true, nullable = false)
	public Integer getIdVille() {
		return this.idVille;
	}

	public void setIdVille(Integer idVille) {
		this.idVille = idVille;
	}

	@Column(name = "intitule", length = 254)
	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ville")
	public Set<Destination> getDestinations() {
		return this.destinations;
	}

	public void setDestinations(Set<Destination> destinations) {
		this.destinations = destinations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ville")
	public Set<Entite> getEntites() {
		return this.entites;
	}

	public void setEntites(Set<Entite> entites) {
		this.entites = entites;
	}

}
